<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <!-- TODO #4889: в проекте ещё остались CS8604, поэтому он тут заглушён.
         Убрать эту строчку вместе с последним исправленным CS8604. -->
    <NoWarn>$(NoWarn);CS8604</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\JoinRpg.Dal.Impl\JoinRpg.Dal.Impl.csproj" />
    <ProjectReference Include="..\JoinRpg.IdPortal\JoinRpg.IdPortal.csproj" />
  </ItemGroup>

</Project>
