// <auto-generated />
namespace JoinRpg.Dal.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FieldsImprovement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FieldsImprovement));
        
        string IMigrationMetadata.Id
        {
            get { return "201512261351297_FieldsImprovement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
