// <auto-generated />
namespace JoinRpg.Dal.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RequireClaimResponsible : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequireClaimResponsible));
        
        string IMigrationMetadata.Id
        {
            get { return "202110241232502_RequireClaimResponsible"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
