// <auto-generated />
namespace JoinRpg.Dal.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CloneSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CloneSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "202505280652499_CloneSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
