// <auto-generated />
namespace JoinRpg.Dal.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ActiveStatusForKogdaIgra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActiveStatusForKogdaIgra));
        
        string IMigrationMetadata.Id
        {
            get { return "202506081240107_ActiveStatusForKogdaIgra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
