// <auto-generated />
namespace JoinRpg.Dal.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class PlotMasterFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlotMasterFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "202606200816138_PlotMasterFlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
