// <auto-generated />
namespace JoinRpg.Dal.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class ClaimResponsibleMasterNoCascade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClaimResponsibleMasterNoCascade));
        
        string IMigrationMetadata.Id
        {
            get { return "202609252020373_ClaimResponsibleMasterNoCascade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
