resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdp.yaml
  - db-migration-job.yaml
  - id-portal-deployment.yaml
  - id-portal-ingress.yaml
  - id-portal-pdp.yaml
  - id-portal-service.yaml

namespace: override-me

secretGenerator:
  - name: joinrpg-main
    envs:
      - joinrpg-main.secret.env
