version: '3'

services:
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:14.2'

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5432:5432

    volumes:
        - ./scripts/postgre-docker-entrypoint-initdb:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_USER: postgres_user # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: qwerty # The PostgreSQL password (useful to connect to the database)
      POSTGRES_MULTIPLE_DATABASES: joinrpg-dev, aspnet-data-protection
