services:
  database:
    # Должно совпадать с версией на которой прод работает
    image: 'postgres:14.2'

    ports:
      - 5432:5432

    volumes:
        - ./scripts/postgre-docker-entrypoint-initdb:/docker-entrypoint-initdb.d
        - joinrpg-sqlserver-data:/var/lib/postgresql/data/

    environment:
      POSTGRES_USER: postgres_user # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: qwerty # The PostgreSQL password (useful to connect to the database)
      POSTGRES_MULTIPLE_DATABASES: joinrpg-dev, aspnet-data-protection, DailyJob, notifications, joinrpg-idportal
      PGDATA: '/var/lib/postgresql/data/pgdata'

  sql-server:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    volumes:
      - joinrpg-pg-data:/var/opt/mssql

    ports:
      - 1433:1433

    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'MsSqlPass1!'
      MSSQL_PID: 'Express'
      MSSQL_COLLATION: 'Cyrillic_General_CI_AS'
      MSSQL_LCID: '1033'
volumes:
 joinrpg-pg-data:
 joinrpg-sqlserver-data:
