// <auto-generated />
using System;
using JoinRpg.Dal.Notifications;
using JoinRpg.PrimitiveTypes.Notifications;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JoinRpg.Dal.Notifications.Migrations
{
    [DbContext(typeof(NotificationsDataDbContext))]
    partial class NotificationsDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_channel", new[] { "email", "show_in_ui" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_message_status", new[] { "failed", "queued", "sending", "sent" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JoinRpg.Dal.Notifications.NotificationMessage", b =>
                {
                    b.Property<int>("NotificationMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationMessageId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityReference")
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("InitiatorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationMessageId");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("JoinRpg.Dal.Notifications.NotificationMessageChannel", b =>
                {
                    b.Property<int>("NotificationMessageChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationMessageChannelId"));

                    b.Property<NotificationChannel>("Channel")
                        .HasColumnType("notification_channel");

                    b.Property<string>("ChannelSpecificValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("NotificationMessageId")
                        .HasColumnType("integer");

                    b.Property<NotificationMessageStatus>("NotificationMessageStatus")
                        .HasColumnType("notification_message_status");

                    b.HasKey("NotificationMessageChannelId");

                    b.HasIndex("NotificationMessageId");

                    b.HasIndex("Channel", "NotificationMessageChannelId")
                        .IsUnique();

                    b.HasIndex("NotificationMessageStatus", "Channel", "NotificationMessageChannelId");

                    b.ToTable("NotificationMessageChannels");
                });

            modelBuilder.Entity("JoinRpg.Dal.Notifications.NotificationMessageChannel", b =>
                {
                    b.HasOne("JoinRpg.Dal.Notifications.NotificationMessage", "NotificationMessage")
                        .WithMany("NotificationMessageChannels")
                        .HasForeignKey("NotificationMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationMessage");
                });

            modelBuilder.Entity("JoinRpg.Dal.Notifications.NotificationMessage", b =>
                {
                    b.Navigation("NotificationMessageChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
