global using JoinRpg.Common.PrimitiveTypes;
global using JoinRpg.Common.PrimitiveTypes.Users;
global using JoinRpg.Data.Interfaces;
global using JoinRpg.DomainTypes;
global using JoinRpg.DomainTypes.ProjectMetadata;
global using JoinRpg.Helpers;
global using JoinRpg.Interfaces;
global using JoinRpg.Services.Interfaces;
global using Microsoft.Extensions.Logging;
