// <auto-generated />
namespace JoinRpg.Dal.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PaymentTypeKind : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PaymentTypeKind));
        
        string IMigrationMetadata.Id
        {
            get { return "201909221853554_PaymentTypeKind"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
