apiVersion: networking.k8s.io/v1beta1
kind: Ingress
{{- $fullName := include "portal.fullname" . }}
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "false"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
    - "www.{{ .Values.ingress.host }}"
    secretName: {{ $fullName }}-tls

  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
            serviceName: {{ $fullName }}
            servicePort: 80
    