<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>JoinRpg.Common.WebComponents</PackageId>
    <Description>Библиотека переиспользуемых Blazor-компонентов Joinrpg.ru (кнопки, диалоги, поля ввода, иконки).</Description>
    <PackageProjectUrl>https://github.com/joinrpg/joinrpg-net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/joinrpg/joinrpg-net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\JoinRpg.Common.PrimitiveTypes\JoinRpg.Common.PrimitiveTypes.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\lib\" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="libman.json" />
    <None Remove="JoinUserLinkEditor.razor.css~RF16470767.TMP" />
    <None Include="libman.json" />
    <None Update="libman.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <InternalsVisibleTo Include="JoinRpg.WebPortal.Models.Test" />
  </ItemGroup>
</Project>
