resources:
  - ../base

namespace: dev

commonLabels:
  managed-by-kustomize-dev: "true" #Careful. Contains name of the environment, used for kubectl apply --prune

patchesJson6902:
  - target:
      kind: Ingress
      group: networking.k8s.io
      version: v1
      name: joinrpg-portal
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.joinrpg.ru
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.joinrpg.ru
      - op: replace
        path: /spec/tls/0/secretName
        value: dev-joinrpg-ru-tls

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: joinrpg-portal
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 300m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 768Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi

  - target:
      group: policy
      version: v1
      kind: PodDisruptionBudget
      name: joinrpg-portal
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
