using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JoinRpg.PrimitiveTypes.SourceGenerator;

[Generator]
public class ProjectEntityIdGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "JoinRpg.PrimitiveTypes.ProjectEntityIdAttribute";
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        using System;
        namespace JoinRpg.PrimitiveTypes;

        /// <summary>Source generator marker for IProjectEntityId implementations.</summary>
        [AttributeUsage(AttributeTargets.Class)]
        internal sealed class ProjectEntityIdAttribute : Attribute
        {
            /// <summary>Short prefix used in ToString (e.g. "ClaimId"). Defaults to TypeName minus "Identification" suffix.</summary>
            public string? ShortName { get; set; }

            /// <summary>Additional prefixes accepted during parsing (e.g. old formats).</summary>
            public string[]? AdditionalPrefixes { get; set; }

            /// <summary>Set to true to skip generating IComparable (use when type needs custom comparison logic).</summary>
            public bool SkipComparable { get; set; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("ProjectEntityIdAttribute.g.cs", AttributeSource));

        var records = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) =>
                    node is RecordDeclarationSyntax r && r.ParameterList != null,
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(records, static (ctx, info) =>
            ctx.AddSource($"{info.FullTypeName}.ProjectEntityId.g.cs", GenerateCode(info)));
    }

    private static TypeGenerationInfo? GetTypeInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetNode is not RecordDeclarationSyntax recordDecl ||
            ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var attrData = ctx.Attributes.FirstOrDefault();
        if (attrData == null)
        {
            return null;
        }

        // Extract attribute properties
        string? shortName = null;
        var additionalPrefixes = new List<string>();
        bool skipComparable = false;

        foreach (var namedArg in attrData.NamedArguments)
        {
            if (namedArg.Key == "ShortName" && namedArg.Value.Value is string sn)
            {
                shortName = sn;
            }
            else if (namedArg.Key == "SkipComparable" && namedArg.Value.Value is bool sc)
            {
                skipComparable = sc;
            }
            else if (namedArg.Key == "AdditionalPrefixes" && !namedArg.Value.IsNull)
            {
                foreach (var v in namedArg.Value.Values)
                {
                    if (v.Value is string s)
                    {
                        additionalPrefixes.Add(s);
                    }
                }
            }
        }

        // Default ShortName: strip "Identification" suffix
        const string identSuffix = "Identification";
        shortName ??= typeSymbol.Name.EndsWith(identSuffix)
            ? typeSymbol.Name.Substring(0, typeSymbol.Name.Length - identSuffix.Length)
            : typeSymbol.Name;

        // Get primary constructor parameters from syntax
        if (recordDecl.ParameterList == null)
        {
            return null;
        }

        var paramList = recordDecl.ParameterList.Parameters;

        if (paramList.Count == 0)
        {
            return null;
        }

        // Resolve parameter types via semantic model
        var parameters = new List<ParameterInfo>();
        foreach (var param in paramList)
        {
            if (param.Type == null)
            {
                continue;
            }

            var typeInfo = ctx.SemanticModel.GetTypeInfo(param.Type);
            var paramTypeSymbol = typeInfo.Type as INamedTypeSymbol;
            if (paramTypeSymbol == null)
            {
                continue;
            }

            var paramKind = ClassifyParamType(paramTypeSymbol, ctx.SemanticModel.Compilation);
            parameters.Add(new ParameterInfo(param.Identifier.Text, paramTypeSymbol, paramKind));
        }

        if (parameters.Count == 0)
        {
            return null;
        }

        // Compute flat leaf expressions
        var flatLeaves = ComputeFlatLeaves(parameters, ctx.SemanticModel.Compilation);
        if (flatLeaves == null)
        {
            return null;
        }

        // Determine namespace
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        // Determine if we need to generate ProjectId property
        bool needsProjectIdProperty = parameters[0].Kind != ParamKind.ProjectIdentification;

        // Determine the last int param name (for IComparable and IProjectEntityId.Id)
        string? lastIntParamName = null;
        for (int i = parameters.Count - 1; i >= 0; i--)
        {
            if (parameters[i].Kind == ParamKind.Int)
            {
                lastIntParamName = parameters[i].Name;
                break;
            }
        }
        if (lastIntParamName == null)
        {
            return null;
        }

        // Determine first nested param name (for ProjectId property)
        string? firstNestedParamName = needsProjectIdProperty ? parameters[0].Name : null;

        return new TypeGenerationInfo(
            FullTypeName: $"{(ns != null ? ns + "." : "")}{typeSymbol.Name}",
            Namespace: ns,
            TypeName: typeSymbol.Name,
            ShortName: shortName,
            AdditionalPrefixes: additionalPrefixes.ToArray(),
            SkipComparable: skipComparable,
            FlatLeafExpressions: flatLeaves,
            NeedsProjectIdProperty: needsProjectIdProperty,
            FirstNestedParamName: firstNestedParamName,
            LastIntParamName: lastIntParamName
        );
    }

    private static List<string>? ComputeFlatLeaves(
        List<ParameterInfo> parameters, Compilation compilation)
    {
        var result = new List<string>();
        foreach (var param in parameters)
        {
            var leaves = GetLeafExpressions(param.Name, param.TypeSymbol, param.Kind, compilation);
            if (leaves == null)
            {
                return null;
            }

            result.AddRange(leaves);
        }
        return result;
    }

    private static List<string>? GetLeafExpressions(
        string accessor, INamedTypeSymbol type, ParamKind kind, Compilation compilation)
    {
        switch (kind)
        {
            case ParamKind.Int:
                return new List<string> { accessor };
            case ParamKind.ProjectIdentification:
                return new List<string> { $"{accessor}.Value" };
            case ParamKind.NestedEntityId:
                return ExpandNestedType(accessor, type, compilation);
            default:
                return null;
        }
    }

    private static List<string>? ExpandNestedType(
        string accessor, INamedTypeSymbol type, Compilation compilation)
    {
        // Find the primary constructor of the nested type (look for [JsonConstructor])
        var primaryCtor = FindPrimaryConstructor(type);
        if (primaryCtor == null)
        {
            return null;
        }

        var result = new List<string>();
        foreach (var param in primaryCtor.Parameters)
        {
            var paramType = param.Type as INamedTypeSymbol;
            if (paramType == null)
            {
                return null;
            }

            var paramKind = ClassifyParamType(paramType, compilation);
            var fullAccessor = $"{accessor}.{param.Name}";

            var leaves = GetLeafExpressions(fullAccessor, paramType, paramKind, compilation);
            if (leaves == null)
            {
                return null;
            }

            result.AddRange(leaves);
        }
        return result;
    }

    private static IMethodSymbol? FindPrimaryConstructor(INamedTypeSymbol type)
    {
        // For records: find constructor with [JsonConstructor] attribute
        var jsonCtorAttr = type.InstanceConstructors
            .FirstOrDefault(c => c.GetAttributes()
                .Any(a => a.AttributeClass?.Name == "JsonConstructorAttribute"));
        if (jsonCtorAttr != null)
        {
            return jsonCtorAttr;
        }

        // Fallback: find constructor that starts with ProjectIdentification or IProjectEntityId
        return type.InstanceConstructors
            .Where(c => !c.IsImplicitlyDeclared && c.Parameters.Length > 0)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault(c =>
            {
                if (c.Parameters.Length == 0)
                {
                    return false;
                }

                var firstParamTypeName = c.Parameters[0].Type.Name;
                return firstParamTypeName == "ProjectIdentification" ||
                       c.Parameters[0].Type.AllInterfaces.Any(i => i.Name == "IProjectEntityId");
            });
    }

    private static ParamKind ClassifyParamType(INamedTypeSymbol type, Compilation compilation)
    {
        if (type.SpecialType == SpecialType.System_Int32)
        {
            return ParamKind.Int;
        }

        if (type.Name == "ProjectIdentification")
        {
            return ParamKind.ProjectIdentification;
        }

        // Check if it implements IProjectEntityId
        var iProjectEntityIdType = compilation.GetTypeByMetadataName("JoinRpg.PrimitiveTypes.IProjectEntityId");
        if (iProjectEntityIdType != null &&
            type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iProjectEntityIdType)))
        {
            return ParamKind.NestedEntityId;
        }

        return ParamKind.Unknown;
    }

    private static string GenerateCode(TypeGenerationInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine();

        if (info.Namespace != null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"public partial record {info.TypeName} : ISpanParsable<{info.TypeName}>");
        sb.AppendLine("{");

        // IProjectEntityId.Id - public so it's accessible directly on the type
        sb.AppendLine($"    public int Id => {info.LastIntParamName};");
        sb.AppendLine();

        // ProjectId property (only if first param is not ProjectIdentification)
        if (info.NeedsProjectIdProperty && info.FirstNestedParamName != null)
        {
            sb.AppendLine($"    public ProjectIdentification ProjectId => {info.FirstNestedParamName}.ProjectId;");
            sb.AppendLine();
        }

        // ToString
        var toStringBody = string.Join("-", info.FlatLeafExpressions.Select(e => $"{{{e}}}"));
        sb.AppendLine($"    public override string ToString() => $\"{info.ShortName}({toStringBody})\";");
        sb.AppendLine();

        // IComparable - public so nested types can call it directly
        if (!info.SkipComparable)
        {
            sb.AppendLine($"    public int CompareTo({info.TypeName}? other)");
            sb.AppendLine($"        => Comparer<int>.Default.Compare({info.LastIntParamName}, other?.{info.LastIntParamName} ?? -1);");
            sb.AppendLine();
        }

        // ISpanParsable
        int leafCount = info.FlatLeafExpressions.Count;

        // Build prefixes array
        var prefixes = new List<string> { $"\"{info.ShortName}\"", $"nameof({info.TypeName})" };
        foreach (var ap in info.AdditionalPrefixes)
        {
            prefixes.Add($"\"{ap}\"");
        }

        var prefixesStr = string.Join(", ", prefixes);

        // Build TryParseN call
        string tryParseCall;
        string constructorArgs;

        if (leafCount == 1)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse1(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value";
        }
        else if (leafCount == 2)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse2(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2";
        }
        else if (leafCount == 3)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse3(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2, parsed.Value.i3";
        }
        else if (leafCount == 4)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse4(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2, parsed.Value.i3, parsed.Value.i4";
        }
        else
        {
            // Not supported - emit a compile error comment
            sb.AppendLine($"    // ERROR: Unsupported leaf count {leafCount}");
            sb.AppendLine("}");
            return sb.ToString();
        }

        sb.AppendLine($"    public static {info.TypeName} Parse(ReadOnlySpan<char> value, IFormatProvider? provider)");
        sb.AppendLine($"        => TryParse(value, provider, out var result) ? result : throw new ArgumentException(\"Could not parse supplied value.\", nameof(value));");
        sb.AppendLine();
        sb.AppendLine($"    public static {info.TypeName} Parse(string value, IFormatProvider? provider)");
        sb.AppendLine($"        => TryParse(value.AsSpan(), provider, out var result) ? result : throw new ArgumentException(\"Could not parse supplied value.\", nameof(value));");
        sb.AppendLine();
        sb.AppendLine($"    static bool IParsable<{info.TypeName}>.TryParse([NotNullWhen(true)] string? value, IFormatProvider? provider, [MaybeNullWhen(false)] out {info.TypeName} result)");
        sb.AppendLine($"        => TryParse(value.AsSpan(), provider, out result);");
        sb.AppendLine();
        sb.AppendLine($"    public static bool TryParse(ReadOnlySpan<char> value, IFormatProvider? provider, [MaybeNullWhen(false)] out {info.TypeName} result)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var parsed = {tryParseCall};");
        sb.AppendLine("        if (parsed != null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {info.TypeName}({constructorArgs});");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        result = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private enum ParamKind { Int, ProjectIdentification, NestedEntityId, Unknown }

    private sealed record ParameterInfo(string Name, INamedTypeSymbol TypeSymbol, ParamKind Kind);

    private sealed record TypeGenerationInfo(
        string FullTypeName,
        string? Namespace,
        string TypeName,
        string ShortName,
        string[] AdditionalPrefixes,
        bool SkipComparable,
        List<string> FlatLeafExpressions,
        bool NeedsProjectIdProperty,
        string? FirstNestedParamName,
        string LastIntParamName
    );
}
