using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JoinRpg.PrimitiveTypes.SourceGenerator;

[Generator]
public class ProjectEntityIdGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "JoinRpg.PrimitiveTypes.ProjectEntityIdAttribute";
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        using System;
        namespace JoinRpg.PrimitiveTypes;

        /// <summary>Маркер для генератора реализаций IProjectEntityId.</summary>
        [AttributeUsage(AttributeTargets.Class)]
        internal sealed class ProjectEntityIdAttribute : Attribute
        {
            /// <summary>Короткий префикс для ToString (например "ClaimId"). По умолчанию — TypeName минус суффикс "Identification" плюс суффикс "Id".</summary>
            public string? ShortName { get; set; }

            /// <summary>Дополнительные префиксы для парсинга (например, старые форматы). По умолчанию ShortName без суффикса "Id" добавляется автоматически.</summary>
            public string[]? AdditionalPrefixes { get; set; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("ProjectEntityIdAttribute.g.cs", AttributeSource));

        var records = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) =>
                    node is RecordDeclarationSyntax r && r.ParameterList != null,
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(records, static (ctx, info) =>
            ctx.AddSource($"{info.FullTypeName}.ProjectEntityId.g.cs", GenerateCode(info)));
    }

    private static TypeGenerationInfo? GetTypeInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetNode is not RecordDeclarationSyntax recordDecl ||
            ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var attrData = ctx.Attributes.FirstOrDefault();
        if (attrData == null)
        {
            return null;
        }

        // Извлекаем свойства атрибута
        string? shortName = null;
        var additionalPrefixes = new List<string>();

        foreach (var namedArg in attrData.NamedArguments)
        {
            if (namedArg.Key == "ShortName" && namedArg.Value.Value is string sn)
            {
                shortName = sn;
            }
            else if (namedArg.Key == "AdditionalPrefixes" && !namedArg.Value.IsNull)
            {
                foreach (var v in namedArg.Value.Values)
                {
                    if (v.Value is string s)
                    {
                        additionalPrefixes.Add(s);
                    }
                }
            }
        }

        // ShortName по умолчанию: TypeName минус суффикс "Identification" плюс суффикс "Id"
        const string identSuffix = "Identification";
        shortName ??= typeSymbol.Name.EndsWith(identSuffix)
            ? typeSymbol.Name.Substring(0, typeSymbol.Name.Length - identSuffix.Length) + "Id"
            : typeSymbol.Name;

        // Авто-добавляем ShortName без суффикса "Id" как дополнительный префикс
        const string idSuffix = "Id";
        if (shortName.EndsWith(idSuffix) && shortName.Length > idSuffix.Length)
        {
            var autoPrefix = shortName.Substring(0, shortName.Length - idSuffix.Length);
            if (!additionalPrefixes.Contains(autoPrefix))
            {
                additionalPrefixes.Insert(0, autoPrefix);
            }
        }

        // Получаем параметры основного конструктора из синтаксиса
        if (recordDecl.ParameterList == null)
        {
            return null;
        }

        var paramList = recordDecl.ParameterList.Parameters;

        if (paramList.Count == 0)
        {
            return null;
        }

        // Определяем типы параметров через семантическую модель
        var parameters = new List<ParameterInfo>();
        foreach (var param in paramList)
        {
            if (param.Type == null)
            {
                continue;
            }

            var typeInfo = ctx.SemanticModel.GetTypeInfo(param.Type);
            var paramTypeSymbol = typeInfo.Type as INamedTypeSymbol;
            if (paramTypeSymbol == null)
            {
                continue;
            }

            var paramKind = ClassifyParamType(paramTypeSymbol, ctx.SemanticModel.Compilation);
            parameters.Add(new ParameterInfo(param.Identifier.Text, paramTypeSymbol, paramKind));
        }

        if (parameters.Count == 0)
        {
            return null;
        }

        // Вычисляем плоские листовые выражения (leaf int expressions)
        var flatLeaves = ComputeFlatLeaves(parameters, ctx.SemanticModel.Compilation);
        if (flatLeaves == null)
        {
            return null;
        }

        // Определяем пространство имён
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        // Нужен ли свой ProjectId property (если первый параметр — не ProjectIdentification)
        bool needsProjectIdProperty = parameters[0].Kind != ParamKind.ProjectIdentification;

        // Последний int-параметр (для IComparable и IProjectEntityId.Id)
        string? lastIntParamName = null;
        for (int i = parameters.Count - 1; i >= 0; i--)
        {
            if (parameters[i].Kind == ParamKind.Int)
            {
                lastIntParamName = parameters[i].Name;
                break;
            }
        }
        if (lastIntParamName == null)
        {
            return null;
        }

        // Первый вложенный параметр (для свойства ProjectId)
        string? firstNestedParamName = needsProjectIdProperty ? parameters[0].Name : null;

        // Информация о параметрах конструктора с количеством листьев для каждого
        var primaryParams = BuildPrimaryParamInfos(parameters, ctx.SemanticModel.Compilation);

        return new TypeGenerationInfo(
            FullTypeName: $"{(ns != null ? ns + "." : "")}{typeSymbol.Name}",
            Namespace: ns,
            TypeName: typeSymbol.Name,
            ShortName: shortName,
            AdditionalPrefixes: additionalPrefixes.ToArray(),
            SkipComparable: HasHandWrittenCompareTo(typeSymbol),
            FlatLeafExpressions: flatLeaves,
            NeedsProjectIdProperty: needsProjectIdProperty,
            FirstNestedParamName: firstNestedParamName,
            LastIntParamName: lastIntParamName,
            PrimaryParams: primaryParams
        );
    }

    private static IReadOnlyList<PrimaryParamInfo> BuildPrimaryParamInfos(
        List<ParameterInfo> parameters, Compilation compilation)
    {
        var result = new List<PrimaryParamInfo>();
        foreach (var param in parameters)
        {
            var leaves = GetLeafExpressions(param.Name, param.TypeSymbol, param.Kind, compilation);
            int leafCount = leaves?.Count ?? 1;
            result.Add(new PrimaryParamInfo(
                Name: param.Name,
                TypeName: param.TypeSymbol.Name,
                Kind: param.Kind,
                LeafCount: leafCount));
        }
        return result;
    }

    private static List<string>? ComputeFlatLeaves(
        List<ParameterInfo> parameters, Compilation compilation)
    {
        var result = new List<string>();
        foreach (var param in parameters)
        {
            var leaves = GetLeafExpressions(param.Name, param.TypeSymbol, param.Kind, compilation);
            if (leaves == null)
            {
                return null;
            }

            result.AddRange(leaves);
        }
        return result;
    }

    private static List<string>? GetLeafExpressions(
        string accessor, INamedTypeSymbol type, ParamKind kind, Compilation compilation)
    {
        switch (kind)
        {
            case ParamKind.Int:
                return new List<string> { accessor };
            case ParamKind.ProjectIdentification:
                return new List<string> { $"{accessor}.Value" };
            case ParamKind.NestedEntityId:
                return ExpandNestedType(accessor, type, compilation);
            default:
                return null;
        }
    }

    private static List<string>? ExpandNestedType(
        string accessor, INamedTypeSymbol type, Compilation compilation)
    {
        // Ищем основной конструктор вложенного типа
        var primaryCtor = FindPrimaryConstructor(type);
        if (primaryCtor == null)
        {
            return null;
        }

        var result = new List<string>();
        foreach (var param in primaryCtor.Parameters)
        {
            var paramType = param.Type as INamedTypeSymbol;
            if (paramType == null)
            {
                return null;
            }

            var paramKind = ClassifyParamType(paramType, compilation);
            var fullAccessor = $"{accessor}.{param.Name}";

            var leaves = GetLeafExpressions(fullAccessor, paramType, paramKind, compilation);
            if (leaves == null)
            {
                return null;
            }

            result.AddRange(leaves);
        }
        return result;
    }

    private static IMethodSymbol? FindPrimaryConstructor(INamedTypeSymbol type)
    {
        // Для record-типов: ищем конструктор с атрибутом [JsonConstructor]
        var jsonCtorAttr = type.InstanceConstructors
            .FirstOrDefault(c => c.GetAttributes()
                .Any(a => a.AttributeClass?.Name == "JsonConstructorAttribute"));
        if (jsonCtorAttr != null)
        {
            return jsonCtorAttr;
        }

        // Запасной вариант: ищем конструктор, начинающийся с ProjectIdentification или IProjectEntityId
        return type.InstanceConstructors
            .Where(c => !c.IsImplicitlyDeclared && c.Parameters.Length > 0)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault(c =>
            {
                if (c.Parameters.Length == 0)
                {
                    return false;
                }

                var firstParamTypeName = c.Parameters[0].Type.Name;
                return firstParamTypeName == "ProjectIdentification" ||
                       c.Parameters[0].Type.AllInterfaces.Any(i => i.Name == "IProjectEntityId");
            });
    }

    /// <summary>Проверяет, есть ли в типе hand-written реализация CompareTo (включая explicit interface implementations).</summary>
    private static bool HasHandWrittenCompareTo(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => !m.IsImplicitlyDeclared)
            .Any(m =>
                (m.Name == "CompareTo" && m.Parameters.Length == 1) ||
                m.ExplicitInterfaceImplementations.Any(ei => ei.Name == "CompareTo"));
    }

    private static ParamKind ClassifyParamType(INamedTypeSymbol type, Compilation compilation)
    {
        if (type.SpecialType == SpecialType.System_Int32)
        {
            return ParamKind.Int;
        }

        if (type.Name == "ProjectIdentification")
        {
            return ParamKind.ProjectIdentification;
        }

        // Проверяем реализацию IProjectEntityId в уже скомпилированном коде
        var iProjectEntityIdType = compilation.GetTypeByMetadataName("JoinRpg.PrimitiveTypes.IProjectEntityId");
        if (iProjectEntityIdType != null &&
            type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iProjectEntityIdType)))
        {
            return ParamKind.NestedEntityId;
        }

        // Также проверяем наличие атрибута [ProjectEntityId] — такие типы реализуют IProjectEntityId
        // через генерируемый код, поэтому в hand-written источнике интерфейс может отсутствовать
        if (type.GetAttributes().Any(a => a.AttributeClass?.Name == "ProjectEntityIdAttribute"))
        {
            return ParamKind.NestedEntityId;
        }

        return ParamKind.Unknown;
    }

    /// <summary>Преобразует leaf-выражение в имя параметра конструктора.</summary>
    private static string LeafToParamName(string leafExpr)
    {
        // Убираем суффикс ".Value" (для ProjectIdentification.Value)
        string withoutValue = leafExpr.EndsWith(".Value")
            ? leafExpr.Substring(0, leafExpr.Length - 6)
            : leafExpr;
        // Берём последний компонент пути (после последней точки)
        int dotIdx = withoutValue.LastIndexOf('.');
        string lastComp = dotIdx >= 0 ? withoutValue.Substring(dotIdx + 1) : withoutValue;
        // Делаем первую букву строчной
        return char.ToLower(lastComp[0]) + lastComp.Substring(1);
    }

    /// <summary>
    /// Строит выражение для реконструкции параметра из листовых int-значений.
    /// leafParamNames[0] может быть как int (flat constructor), так и ProjectIdentification (2nd-level constructor).
    /// </summary>
    private static string BuildReconstructExpression(PrimaryParamInfo param, string[] leafParamNames)
    {
        return param.Kind switch
        {
            ParamKind.Int => leafParamNames[0],
            ParamKind.ProjectIdentification => $"new ProjectIdentification({leafParamNames[0]})",
            // Для NestedEntityId: new NT(leaf1, leaf2, ...) — C# выбирает нужный конструктор по типу leaf1
            ParamKind.NestedEntityId => $"new {param.TypeName}({string.Join(", ", leafParamNames)})",
            _ => "/* Ошибка: неизвестный тип параметра */"
        };
    }

    private static string GenerateCode(TypeGenerationInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        if (info.Namespace != null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        // Генерируемые интерфейсы
        var interfaces = new List<string> { "IProjectEntityId", $"ISpanParsable<{info.TypeName}>" };
        if (!info.SkipComparable)
        {
            interfaces.Add($"IComparable<{info.TypeName}>");
        }

        sb.AppendLine($"public partial record {info.TypeName} : {string.Join(", ", interfaces)}");
        sb.AppendLine("{");

        // Свойство Id из IProjectEntityId
        sb.AppendLine($"    public int Id => {info.LastIntParamName};");
        sb.AppendLine();

        // Свойство ProjectId (только если первый параметр — не ProjectIdentification)
        if (info.NeedsProjectIdProperty && info.FirstNestedParamName != null)
        {
            sb.AppendLine($"    public ProjectIdentification ProjectId => {info.FirstNestedParamName}.ProjectId;");
            sb.AppendLine();
        }

        // ToString
        var toStringBody = string.Join("-", info.FlatLeafExpressions.Select(e => $"{{{e}}}"));
        sb.AppendLine($"    public override string ToString() => $\"{info.ShortName}({toStringBody})\";");
        sb.AppendLine();

        // IComparable<T>
        if (!info.SkipComparable)
        {
            sb.AppendLine($"    public int CompareTo({info.TypeName}? other)");
            sb.AppendLine($"        => Comparer<int>.Default.Compare({info.LastIntParamName}, other?.{info.LastIntParamName} ?? -1);");
            sb.AppendLine();
        }

        // Листовые имена параметров для конструкторов
        var leafParamNames = info.FlatLeafExpressions.Select(LeafToParamName).ToList();
        int leafCount = leafParamNames.Count;

        // Конструктор с плоскими int-параметрами (для всех типов с 2+ параметрами)
        if (leafCount >= 2)
        {
            var intParams = string.Join(", ", leafParamNames.Select(n => $"int {n}"));
            var ctorArgs = BuildConstructorArgs(info.PrimaryParams, leafParamNames);
            sb.AppendLine($"    public {info.TypeName}({intParams})");
            sb.AppendLine($"        : this({ctorArgs}) {{ }}");
            sb.AppendLine();
        }

        // Конструктор с ProjectIdentification (для типов, где первый параметр — вложенный IProjectEntityId)
        if (leafCount >= 3 && info.PrimaryParams[0].Kind == ParamKind.NestedEntityId)
        {
            var projParams = $"ProjectIdentification {leafParamNames[0]}, " +
                string.Join(", ", leafParamNames.Skip(1).Select(n => $"int {n}"));
            var projArgs = BuildConstructorArgs(info.PrimaryParams, leafParamNames);
            sb.AppendLine($"    public {info.TypeName}({projParams})");
            sb.AppendLine($"        : this({projArgs}) {{ }}");
            sb.AppendLine();
        }

        // Метод FromOptional — все параметры nullable
        GenerateFromOptional(sb, info);

        // Метод FromOptional(int, int?) с проверкой -1 — для всех (ProjectIdentification, int) типов (-1 всегда считается null)
        if (info.PrimaryParams.Count == 2 &&
            info.PrimaryParams[0].Kind == ParamKind.ProjectIdentification &&
            info.PrimaryParams[1].Kind == ParamKind.Int)
        {
            var entityParam = info.PrimaryParams[1].Name;
            var entityParamLower = char.ToLower(entityParam[0]) + entityParam.Substring(1);
            sb.AppendLine($"    public static {info.TypeName}? FromOptional(int projectId, int? {entityParamLower})");
            sb.AppendLine($"        => {entityParamLower} is not null && {entityParamLower} != -1 ? new {info.TypeName}(projectId, {entityParamLower}.Value) : null;");
            sb.AppendLine();
        }

        // Метод FromList — только для (ProjectIdentification, int) типов
        if (info.PrimaryParams.Count == 2 &&
            info.PrimaryParams[0].Kind == ParamKind.ProjectIdentification &&
            info.PrimaryParams[1].Kind == ParamKind.Int)
        {
            var entityIdParam = info.PrimaryParams[1].Name;
            sb.AppendLine($"    public static IEnumerable<{info.TypeName}> FromList(IEnumerable<int> list, ProjectIdentification projectId)");
            sb.AppendLine($"        => list.Select(id => new {info.TypeName}(projectId, id));");
            sb.AppendLine();
        }

        // Реализация ISpanParsable<T>
        GenerateISpanParsable(sb, info, leafParamNames);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildConstructorArgs(
        IReadOnlyList<PrimaryParamInfo> primaryParams, List<string> leafParamNames)
    {
        var args = new List<string>();
        int leafIdx = 0;
        foreach (var param in primaryParams)
        {
            var paramLeaves = leafParamNames.Skip(leafIdx).Take(param.LeafCount).ToArray();
            leafIdx += param.LeafCount;
            args.Add(BuildReconstructExpression(param, paramLeaves));
        }
        return string.Join(", ", args);
    }

    private static void GenerateFromOptional(StringBuilder sb, TypeGenerationInfo info)
    {
        // Строим параметры: int → int?, остальные reference types → T?
        var optParams = new List<string>();
        var nullChecks = new List<string>();
        var ctorArgs = new List<string>();

        foreach (var param in info.PrimaryParams)
        {
            var paramNameLower = char.ToLower(param.Name[0]) + param.Name.Substring(1);
            if (param.Kind == ParamKind.Int)
            {
                optParams.Add($"int? {paramNameLower}");
                nullChecks.Add($"{paramNameLower} is not null");
                ctorArgs.Add($"{paramNameLower}.Value");
            }
            else
            {
                // ProjectIdentification и NestedEntityId — reference types, nullable через ?
                optParams.Add($"{param.TypeName}? {paramNameLower}");
                nullChecks.Add($"{paramNameLower} is not null");
                ctorArgs.Add(paramNameLower);
            }
        }

        var paramsStr = string.Join(", ", optParams);
        var checksStr = string.Join(" && ", nullChecks);
        var argsStr = string.Join(", ", ctorArgs);

        sb.AppendLine($"    public static {info.TypeName}? FromOptional({paramsStr})");
        sb.AppendLine($"        => {checksStr} ? new {info.TypeName}({argsStr}) : null;");
        sb.AppendLine();
    }

    private static void GenerateISpanParsable(
        StringBuilder sb, TypeGenerationInfo info, List<string> leafParamNames)
    {
        int leafCount = leafParamNames.Count;

        // Строим массив префиксов
        var prefixes = new List<string> { $"\"{info.ShortName}\"", $"nameof({info.TypeName})" };
        foreach (var ap in info.AdditionalPrefixes)
        {
            prefixes.Add($"\"{ap}\"");
        }

        var prefixesStr = string.Join(", ", prefixes);

        // Выбираем нужный TryParseN и аргументы для конструктора
        string tryParseCall;
        string constructorArgs;

        if (leafCount == 1)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse1(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value";
        }
        else if (leafCount == 2)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse2(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2";
        }
        else if (leafCount == 3)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse3(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2, parsed.Value.i3";
        }
        else if (leafCount == 4)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse4(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2, parsed.Value.i3, parsed.Value.i4";
        }
        else
        {
            // Не поддерживается — выдаём ошибку компиляции
            sb.AppendLine($"    // ОШИБКА: не поддерживается количество листьев {leafCount}");
            return;
        }

        sb.AppendLine($"    public static {info.TypeName} Parse(ReadOnlySpan<char> value, IFormatProvider? provider)");
        sb.AppendLine($"        => TryParse(value, provider, out var result) ? result : throw new ArgumentException(\"Could not parse supplied value.\", nameof(value));");
        sb.AppendLine();
        sb.AppendLine($"    public static {info.TypeName} Parse(string value, IFormatProvider? provider)");
        sb.AppendLine($"        => TryParse(value.AsSpan(), provider, out var result) ? result : throw new ArgumentException(\"Could not parse supplied value.\", nameof(value));");
        sb.AppendLine();
        sb.AppendLine($"    static bool IParsable<{info.TypeName}>.TryParse([NotNullWhen(true)] string? value, IFormatProvider? provider, [MaybeNullWhen(false)] out {info.TypeName} result)");
        sb.AppendLine($"        => TryParse(value.AsSpan(), provider, out result);");
        sb.AppendLine();
        sb.AppendLine($"    public static bool TryParse(ReadOnlySpan<char> value, IFormatProvider? provider, [MaybeNullWhen(false)] out {info.TypeName} result)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var parsed = {tryParseCall};");
        sb.AppendLine("        if (parsed != null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {info.TypeName}({constructorArgs});");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        result = null;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
    }

    private enum ParamKind { Int, ProjectIdentification, NestedEntityId, Unknown }

    private sealed record ParameterInfo(string Name, INamedTypeSymbol TypeSymbol, ParamKind Kind);

    private sealed record PrimaryParamInfo(
        string Name,      // Имя параметра, например "ClaimId"
        string TypeName,  // Имя типа, например "ClaimIdentification" или "int"
        ParamKind Kind,   // Вид параметра
        int LeafCount     // Количество листовых int-значений
    );

    private sealed record TypeGenerationInfo(
        string FullTypeName,
        string? Namespace,
        string TypeName,
        string ShortName,
        string[] AdditionalPrefixes,
        bool SkipComparable,
        List<string> FlatLeafExpressions,
        bool NeedsProjectIdProperty,
        string? FirstNestedParamName,
        string LastIntParamName,
        IReadOnlyList<PrimaryParamInfo> PrimaryParams
    );
}
