using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace JoinRpg.PrimitiveTypes.SourceGenerator;

[Generator]
public class TypedEntityIdGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "JoinRpg.PrimitiveTypes.TypedEntityIdAttribute";
    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        using System;
        namespace JoinRpg.PrimitiveTypes;

        /// <summary>Маркер для генератора реализаций типизированных идентификаторов.</summary>
        [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
        internal sealed class TypedEntityIdAttribute : Attribute
        {
            /// <summary>Короткий префикс для ToString (например "ClaimId"). По умолчанию — TypeName минус суффикс "Identification" плюс суффикс "Id".</summary>
            public string? ShortName { get; set; }

            /// <summary>Дополнительные префиксы для парсинга (например, старые форматы). По умолчанию ShortName без суффикса "Id" добавляется автоматически.</summary>
            public string[]? AdditionalPrefixes { get; set; }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("TypedEntityIdAttribute.g.cs", AttributeSource));

        var records = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) =>
                    node is RecordDeclarationSyntax r && r.ParameterList != null,
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        context.RegisterSourceOutput(records, static (ctx, info) =>
            ctx.AddSource($"{info.FullTypeName}.TypedEntityId.g.cs", GenerateCode(info)));
    }

    private static TypeGenerationInfo? GetTypeInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetNode is not RecordDeclarationSyntax recordDecl ||
            ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var attrData = ctx.Attributes.FirstOrDefault();
        if (attrData == null)
        {
            return null;
        }

        // Извлекаем свойства атрибута
        string? shortName = null;
        var additionalPrefixes = new List<string>();

        foreach (var namedArg in attrData.NamedArguments)
        {
            if (namedArg.Key == "ShortName" && namedArg.Value.Value is string sn)
            {
                shortName = sn;
            }
            else if (namedArg.Key == "AdditionalPrefixes" && !namedArg.Value.IsNull)
            {
                foreach (var v in namedArg.Value.Values)
                {
                    if (v.Value is string s)
                    {
                        additionalPrefixes.Add(s);
                    }
                }
            }
        }

        // ShortName по умолчанию: TypeName минус суффикс "Identification" плюс суффикс "Id"
        const string identSuffix = "Identification";
        shortName ??= typeSymbol.Name.EndsWith(identSuffix)
            ? typeSymbol.Name.Substring(0, typeSymbol.Name.Length - identSuffix.Length) + "Id"
            : typeSymbol.Name;

        // Авто-добавляем ShortName без суффикса "Id" как дополнительный префикс
        const string idSuffix = "Id";
        if (shortName.EndsWith(idSuffix) && shortName.Length > idSuffix.Length)
        {
            var autoPrefix = shortName.Substring(0, shortName.Length - idSuffix.Length);
            if (!additionalPrefixes.Contains(autoPrefix))
            {
                additionalPrefixes.Insert(0, autoPrefix);
            }
        }

        // Получаем параметры основного конструктора из синтаксиса
        if (recordDecl.ParameterList == null)
        {
            return null;
        }

        var paramList = recordDecl.ParameterList.Parameters;

        if (paramList.Count == 0)
        {
            return null;
        }

        // Определяем типы параметров через семантическую модель
        var parameters = new List<ParameterInfo>();
        foreach (var param in paramList)
        {
            if (param.Type == null)
            {
                continue;
            }

            var typeInfo = ctx.SemanticModel.GetTypeInfo(param.Type);
            var paramTypeSymbol = typeInfo.Type as INamedTypeSymbol;
            if (paramTypeSymbol == null)
            {
                continue;
            }

            var paramKind = ClassifyParamType(paramTypeSymbol, ctx.SemanticModel.Compilation);
            if (paramKind == ParamKind.Unknown)
            {
                // Неизвестный тип — не можем сгенерировать код
                return null;
            }
            bool isParamStruct = paramTypeSymbol.TypeKind == TypeKind.Struct;
            parameters.Add(new ParameterInfo(param.Identifier.Text, paramTypeSymbol, paramKind, isParamStruct));
        }

        if (parameters.Count == 0)
        {
            return null;
        }

        // Вычисляем плоские листовые выражения (leaf int expressions)
        var flatLeaves = ComputeFlatLeaves(parameters, ctx.SemanticModel.Compilation);
        if (flatLeaves == null)
        {
            return null;
        }

        // Определяем пространство имён
        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        // Последний int-параметр (для IComparable и Id)
        string? lastIntParamName = null;
        for (int i = parameters.Count - 1; i >= 0; i--)
        {
            if (parameters[i].Kind == ParamKind.Int)
            {
                lastIntParamName = parameters[i].Name;
                break;
            }
        }
        if (lastIntParamName == null)
        {
            return null;
        }

        // Информация о параметрах конструктора с количеством листьев для каждого
        var primaryParams = BuildPrimaryParamInfos(parameters, ctx.SemanticModel.Compilation);

        // Вычисляем вложенные свойства через раскручивание цепочки первых параметров NestedEntityId
        var nestedProperties = ComputeNestedProperties(typeSymbol, parameters, ctx.SemanticModel.Compilation);

        bool isStruct = recordDecl.ClassOrStructKeyword.IsKind(SyntaxKind.StructKeyword);

        return new TypeGenerationInfo(
            FullTypeName: $"{(ns != null ? ns + "." : "")}{typeSymbol.Name}",
            Namespace: ns,
            TypeName: typeSymbol.Name,
            ShortName: shortName,
            AdditionalPrefixes: additionalPrefixes.ToArray(),
            SkipComparable: HasHandWrittenCompareTo(typeSymbol),
            FlatLeafExpressions: flatLeaves,
            LastIntParamName: lastIntParamName,
            PrimaryParams: primaryParams,
            NestedProperties: nestedProperties,
            IsStruct: isStruct
        );
    }

    /// <summary>
    /// Раскручивает цепочку первых параметров NestedEntityId и собирает свойства для генерации.
    /// Например, для ForumCommentIdentification(ForumThreadIdentification ThreadId, ...) генерирует
    /// ProjectId => ThreadId.ProjectId, следуя по цепочке первых параметров.
    /// Свойства, уже объявленные вручную в типе, пропускаются (но цепочка продолжается).
    /// </summary>
    private static List<NestedPropertyInfo> ComputeNestedProperties(
        INamedTypeSymbol currentType,
        List<ParameterInfo> parameters,
        Compilation compilation)
    {
        var result = new List<NestedPropertyInfo>();

        if (parameters.Count == 0 || parameters[0].Kind != ParamKind.NestedEntityId)
        {
            return result;
        }

        var currentTypeSym = parameters[0].TypeSymbol;
        var accessor = parameters[0].Name;

        while (true)
        {
            var ctor = FindPrimaryConstructor(currentTypeSym);
            if (ctor == null || ctor.Parameters.Length == 0)
            {
                break;
            }

            var firstInner = ctor.Parameters[0];
            if (firstInner.Type is not INamedTypeSymbol firstInnerType)
            {
                break;
            }

            var firstInnerKind = ClassifyParamType(firstInnerType, compilation);
            if (firstInnerKind != ParamKind.NestedEntityId)
            {
                break;
            }

            var propName = firstInner.Name;
            var innerAccessor = $"{accessor}.{propName}";

            // Генерируем свойство только если оно не объявлено вручную
            if (!currentType.GetMembers(propName).OfType<IPropertySymbol>()
                .Any(p => !p.IsImplicitlyDeclared))
            {
                result.Add(new NestedPropertyInfo(propName, firstInnerType.Name, innerAccessor));
            }

            // Продолжаем цепочку вне зависимости от того, сгенерировали ли свойство
            currentTypeSym = firstInnerType;
            accessor = innerAccessor;
        }

        return result;
    }

    private static IReadOnlyList<PrimaryParamInfo> BuildPrimaryParamInfos(
        List<ParameterInfo> parameters, Compilation compilation)
    {
        var result = new List<PrimaryParamInfo>();
        foreach (var param in parameters)
        {
            var leaves = GetLeafExpressions(param.Name, param.TypeSymbol, param.Kind, compilation);
            int leafCount = leaves?.Count ?? 1;
            result.Add(new PrimaryParamInfo(
                Name: param.Name,
                TypeName: param.TypeSymbol.Name,
                Kind: param.Kind,
                LeafCount: leafCount,
                IsStruct: param.IsStruct));
        }
        return result;
    }

    private static List<string>? ComputeFlatLeaves(
        List<ParameterInfo> parameters, Compilation compilation)
    {
        var result = new List<string>();
        foreach (var param in parameters)
        {
            var leaves = GetLeafExpressions(param.Name, param.TypeSymbol, param.Kind, compilation);
            if (leaves == null)
            {
                return null;
            }

            result.AddRange(leaves);
        }
        return result;
    }

    private static List<string>? GetLeafExpressions(
        string accessor, INamedTypeSymbol type, ParamKind kind, Compilation compilation)
    {
        switch (kind)
        {
            case ParamKind.Int:
                return new List<string> { accessor };
            case ParamKind.NestedEntityId:
                return ExpandNestedType(accessor, type, compilation);
            default:
                return null;
        }
    }

    private static List<string>? ExpandNestedType(
        string accessor, INamedTypeSymbol type, Compilation compilation)
    {
        // Ищем основной конструктор вложенного типа по [JsonConstructor]
        var primaryCtor = FindPrimaryConstructor(type);
        if (primaryCtor == null)
        {
            return null;
        }

        var result = new List<string>();
        foreach (var param in primaryCtor.Parameters)
        {
            var paramType = param.Type as INamedTypeSymbol;
            if (paramType == null)
            {
                return null;
            }

            var paramKind = ClassifyParamType(paramType, compilation);
            if (paramKind == ParamKind.Unknown)
            {
                return null;
            }

            var fullAccessor = $"{accessor}.{param.Name}";

            var leaves = GetLeafExpressions(fullAccessor, paramType, paramKind, compilation);
            if (leaves == null)
            {
                return null;
            }

            result.AddRange(leaves);
        }
        return result;
    }

    private static IMethodSymbol? FindPrimaryConstructor(INamedTypeSymbol type)
    {
        // Для record-типов: ищем конструктор с атрибутом [JsonConstructor]
        return type.InstanceConstructors
            .FirstOrDefault(c => c.GetAttributes()
                .Any(a => a.AttributeClass?.Name == "JsonConstructorAttribute"));
    }

    /// <summary>Проверяет, есть ли в типе hand-written реализация CompareTo (включая explicit interface implementations).</summary>
    private static bool HasHandWrittenCompareTo(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => !m.IsImplicitlyDeclared)
            .Any(m =>
                (m.Name == "CompareTo" && m.Parameters.Length == 1) ||
                m.ExplicitInterfaceImplementations.Any(ei => ei.Name == "CompareTo"));
    }

    private static ParamKind ClassifyParamType(INamedTypeSymbol type, Compilation compilation)
    {
        if (type.SpecialType == SpecialType.System_Int32)
        {
            return ParamKind.Int;
        }

        // Тип помечен [TypedEntityId] — это вложенный типизированный Id
        if (type.GetAttributes().Any(a => a.AttributeClass?.Name == "TypedEntityIdAttribute"))
        {
            return ParamKind.NestedEntityId;
        }

        // Проверяем реализацию IProjectEntityId в уже скомпилированном коде
        var iProjectEntityIdType = compilation.GetTypeByMetadataName("JoinRpg.PrimitiveTypes.IProjectEntityId");
        if (iProjectEntityIdType != null &&
            type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iProjectEntityIdType)))
        {
            return ParamKind.NestedEntityId;
        }

        return ParamKind.Unknown;
    }

    /// <summary>Преобразует leaf-выражение в имя параметра конструктора.</summary>
    private static string LeafToParamName(string leafExpr)
    {
        // Берём последний компонент пути (после последней точки)
        int dotIdx = leafExpr.LastIndexOf('.');
        string lastComp = dotIdx >= 0 ? leafExpr.Substring(dotIdx + 1) : leafExpr;
        // Делаем первую букву строчной
        return char.ToLower(lastComp[0]) + lastComp.Substring(1);
    }

    /// <summary>
    /// Строит выражение для реконструкции параметра из листовых int-значений.
    /// </summary>
    private static string BuildReconstructExpression(PrimaryParamInfo param, string[] leafParamNames)
    {
        return param.Kind switch
        {
            ParamKind.Int => leafParamNames[0],
            // Для NestedEntityId: new NT(leaf1, leaf2, ...) — C# выбирает нужный конструктор по типу leaf1
            ParamKind.NestedEntityId => $"new {param.TypeName}({string.Join(", ", leafParamNames)})",
            _ => "/* Ошибка: неизвестный тип параметра */"
        };
    }

    private static string GenerateCode(TypeGenerationInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();

        if (info.Namespace != null)
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        // Генерируемые интерфейсы
        var interfaces = new List<string>
        {
            $"ISpanParsable<{info.TypeName}>"
        };
        if (!info.SkipComparable)
        {
            interfaces.Add($"IComparable<{info.TypeName}>");
        }

        string recordKind = info.IsStruct ? "record struct" : "record";
        sb.AppendLine($"public partial {recordKind} {info.TypeName} : {string.Join(", ", interfaces)}");
        sb.AppendLine("{");

        // Свойство Id — генерируется безусловно для всех TypedEntityId
        sb.AppendLine($"    public int Id => {info.LastIntParamName};");
        sb.AppendLine();

        // Неявное преобразование к int — только для не составных id (ровно одно свойство)
        if (info.PrimaryParams.Count == 1)
        {
            sb.AppendLine($"    public static implicit operator int({info.TypeName} self) => self.{info.LastIntParamName};");
            sb.AppendLine();
        }

        // Вложенные свойства, полученные раскручиванием цепочки первых параметров NestedEntityId
        foreach (var nestedProp in info.NestedProperties)
        {
            sb.AppendLine($"    public {nestedProp.PropTypeName} {nestedProp.PropName} => {nestedProp.Accessor};");
            sb.AppendLine();
        }

        // ToString
        var toStringBody = string.Join("-", info.FlatLeafExpressions.Select(e => $"{{{e}}}"));
        sb.AppendLine($"    public override string ToString() => $\"{info.ShortName}({toStringBody})\";");
        sb.AppendLine();

        // IComparable<T>
        if (!info.SkipComparable)
        {
            if (info.IsStruct)
            {
                // Для struct: IComparable<T>.CompareTo(T other) без nullable
                sb.AppendLine($"    public int CompareTo({info.TypeName} other)");
                sb.AppendLine($"        => Comparer<int>.Default.Compare({info.LastIntParamName}, other.{info.LastIntParamName});");
            }
            else
            {
                sb.AppendLine($"    public int CompareTo({info.TypeName}? other)");
                sb.AppendLine($"        => Comparer<int>.Default.Compare({info.LastIntParamName}, other?.{info.LastIntParamName} ?? -1);");
            }
            sb.AppendLine();
        }

        // Листовые имена параметров для конструкторов
        var leafParamNames = info.FlatLeafExpressions.Select(LeafToParamName).ToList();
        int leafCount = leafParamNames.Count;

        // Конструктор с плоскими int-параметрами (для всех типов с 2+ листьями)
        if (leafCount >= 2)
        {
            var intParams = string.Join(", ", leafParamNames.Select(n => $"int {n}"));
            var ctorArgs = BuildConstructorArgs(info.PrimaryParams, leafParamNames);
            sb.AppendLine($"    public {info.TypeName}({intParams})");
            sb.AppendLine($"        : this({ctorArgs}) {{ }}");
            sb.AppendLine();
        }

        // Метод FromOptional — все параметры nullable
        GenerateFromOptional(sb, info);

        // Метод FromOptional(firstLeaf, int?) — для (NestedEntityId с 1 листом, int) типов
        // Не генерируем для struct-типов: неявная конвертация struct→int создаёт неоднозначность с FromOptional(T?, int?)
        if (info.PrimaryParams.Count == 2 &&
            info.PrimaryParams[0].Kind == ParamKind.NestedEntityId &&
            info.PrimaryParams[0].LeafCount == 1 &&
            !info.PrimaryParams[0].IsStruct &&
            info.PrimaryParams[1].Kind == ParamKind.Int)
        {
            var entityParam = info.PrimaryParams[1].Name;
            var entityParamLower = char.ToLower(entityParam[0]) + entityParam.Substring(1);
            var firstLeafParamName = leafParamNames[0];
            sb.AppendLine($"    public static {info.TypeName}? FromOptional(int {firstLeafParamName}, int? {entityParamLower})");
            sb.AppendLine($"        => {entityParamLower} is not null && {entityParamLower} != -1 ? new {info.TypeName}({firstLeafParamName}, {entityParamLower}.Value) : null;");
            sb.AppendLine();
        }

        // Метод FromList — для типов с 2 параметрами, где последний int
        if (info.PrimaryParams.Count == 2 &&
            info.PrimaryParams[1].Kind == ParamKind.Int)
        {
            var firstParamTypeName = info.PrimaryParams[0].TypeName;
            var firstParamVarName = char.ToLower(info.PrimaryParams[0].Name[0]) + info.PrimaryParams[0].Name.Substring(1);
            sb.AppendLine($"    public static IEnumerable<{info.TypeName}> FromList(IEnumerable<int> list, {firstParamTypeName} {firstParamVarName})");
            sb.AppendLine($"        => list.Select(id => new {info.TypeName}({firstParamVarName}, id));");
            sb.AppendLine();
        }

        // Реализация ISpanParsable<T>
        GenerateISpanParsable(sb, info, leafParamNames);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildConstructorArgs(
        IReadOnlyList<PrimaryParamInfo> primaryParams, List<string> leafParamNames)
    {
        var args = new List<string>();
        int leafIdx = 0;
        foreach (var param in primaryParams)
        {
            var paramLeaves = leafParamNames.Skip(leafIdx).Take(param.LeafCount).ToArray();
            leafIdx += param.LeafCount;
            args.Add(BuildReconstructExpression(param, paramLeaves));
        }
        return string.Join(", ", args);
    }

    private static void GenerateFromOptional(StringBuilder sb, TypeGenerationInfo info)
    {
        // Строим параметры: int → int?, остальные reference types → T?
        var optParams = new List<string>();
        var nullChecks = new List<string>();
        var ctorArgs = new List<string>();

        foreach (var param in info.PrimaryParams)
        {
            var paramNameLower = char.ToLower(param.Name[0]) + param.Name.Substring(1);
            if (param.Kind == ParamKind.Int)
            {
                optParams.Add($"int? {paramNameLower}");
                nullChecks.Add($"{paramNameLower} is not null");
                ctorArgs.Add($"{paramNameLower}.Value");
            }
            else
            {
                // NestedEntityId — nullable через ?
                optParams.Add($"{param.TypeName}? {paramNameLower}");
                nullChecks.Add($"{paramNameLower} is not null");
                // Для value types нужен .Value для распаковки из Nullable<T>
                ctorArgs.Add(param.IsStruct ? $"{paramNameLower}.Value" : paramNameLower);
            }
        }

        var paramsStr = string.Join(", ", optParams);
        var checksStr = string.Join(" && ", nullChecks);
        var argsStr = string.Join(", ", ctorArgs);

        sb.AppendLine($"    public static {info.TypeName}? FromOptional({paramsStr})");
        sb.AppendLine($"        => {checksStr} ? new {info.TypeName}({argsStr}) : null;");
        sb.AppendLine();
    }

    private static void GenerateISpanParsable(
        StringBuilder sb, TypeGenerationInfo info, List<string> leafParamNames)
    {
        int leafCount = leafParamNames.Count;

        // Строим массив префиксов
        var prefixes = new List<string> { $"\"{info.ShortName}\"", $"nameof({info.TypeName})" };
        foreach (var ap in info.AdditionalPrefixes)
        {
            prefixes.Add($"\"{ap}\"");
        }

        var prefixesStr = string.Join(", ", prefixes);

        // Выбираем нужный TryParseN и аргументы для конструктора
        string tryParseCall;
        string constructorArgs;

        if (leafCount == 1)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse1(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value";
        }
        else if (leafCount == 2)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse2(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2";
        }
        else if (leafCount == 3)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse3(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2, parsed.Value.i3";
        }
        else if (leafCount == 4)
        {
            tryParseCall = $"IdentificationParseHelper.TryParse4(value, provider, [{prefixesStr}])";
            constructorArgs = "parsed.Value.i1, parsed.Value.i2, parsed.Value.i3, parsed.Value.i4";
        }
        else
        {
            // Не поддерживается — выдаём ошибку компиляции
            sb.AppendLine($"    // ОШИБКА: не поддерживается количество листьев {leafCount}");
            return;
        }

        sb.AppendLine($"    public static {info.TypeName} Parse(ReadOnlySpan<char> value, IFormatProvider? provider)");
        sb.AppendLine($"        => TryParse(value, provider, out var result) ? result : throw new ArgumentException(\"Could not parse supplied value.\", nameof(value));");
        sb.AppendLine();
        sb.AppendLine($"    public static {info.TypeName} Parse(string value, IFormatProvider? provider)");
        sb.AppendLine($"        => TryParse(value.AsSpan(), provider, out var result) ? result : throw new ArgumentException(\"Could not parse supplied value.\", nameof(value));");
        sb.AppendLine();
        sb.AppendLine($"    static bool IParsable<{info.TypeName}>.TryParse([NotNullWhen(true)] string? value, IFormatProvider? provider, [MaybeNullWhen(false)] out {info.TypeName} result)");
        sb.AppendLine($"        => TryParse(value.AsSpan(), provider, out result);");
        sb.AppendLine();
        sb.AppendLine($"    public static bool TryParse(ReadOnlySpan<char> value, IFormatProvider? provider, [MaybeNullWhen(false)] out {info.TypeName} result)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var parsed = {tryParseCall};");
        sb.AppendLine("        if (parsed != null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            result = new {info.TypeName}({constructorArgs});");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        string nullResult = info.IsStruct ? "default" : "null";
        sb.AppendLine($"        result = {nullResult};");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");
    }

    private enum ParamKind { Int, NestedEntityId, Unknown }

    private sealed record ParameterInfo(string Name, INamedTypeSymbol TypeSymbol, ParamKind Kind, bool IsStruct);

    private sealed record PrimaryParamInfo(
        string Name,      // Имя параметра, например "ClaimId"
        string TypeName,  // Имя типа, например "ClaimIdentification" или "int"
        ParamKind Kind,   // Вид параметра
        int LeafCount,    // Количество листовых int-значений
        bool IsStruct     // Является ли тип value type (record struct)
    );

    private sealed record NestedPropertyInfo(
        string PropName,      // Имя свойства, например "ProjectId"
        string PropTypeName,  // Имя типа свойства, например "ProjectIdentification"
        string Accessor       // Выражение для получения значения, например "ThreadId.ProjectId"
    );

    private sealed record TypeGenerationInfo(
        string FullTypeName,
        string? Namespace,
        string TypeName,
        string ShortName,
        string[] AdditionalPrefixes,
        bool SkipComparable,
        List<string> FlatLeafExpressions,
        string LastIntParamName,
        IReadOnlyList<PrimaryParamInfo> PrimaryParams,
        IReadOnlyList<NestedPropertyInfo> NestedProperties,
        bool IsStruct
    );
}
