<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- TODO #4889: в проекте ещё остались CS8604, поэтому он тут заглушён.
         Убрать эту строчку вместе с последним исправленным CS8604. -->
    <NoWarn>$(NoWarn);CS8604</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
	  <PackageReference Include="Shouldly" />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JoinRpg.Services.Notifications\JoinRpg.Services.Notifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
