name: Publish NuGet packages

on:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  publish-nuget:
    name: Pack and publish ${{ matrix.project }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write  # 🔐 Для trusted publishing через OIDC
    strategy:
      matrix:
        project:
          - JoinRpg.Common.WebInfrastructure
          - JoinRpg.Common.PrimitiveTypes
          - JoinRpg.Common.PrimitiveTypes.SourceGenerator
          - JoinRpg.Common.KogdaIgraClient
          # Добавить новые проекты сюда:
          # - SomeOtherProject.csproj

    steps:
      - name: NuGet Login (trusted publishing)
        id: nuget-login
        uses: NuGet/login@v1
        with:
          user: leotsarev
          
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Git Version
        id: version
        run: iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/AntonSmolkov/HandyPoshScripts/v1.0.2/DevOps/SemVerCalc_GitHubFlow_Actions.ps1'))
        shell: pwsh
        env:
          REF_NAME: ${{ github.ref_name }}
          REF_TYPE: ${{ github.ref_type }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: "Directory.Packages.props"

      - name: Locate project
        id: locate-project
        run: echo "PROJECT_FILENAME=$(dotnet sln list | grep ${{ matrix.project }}.csproj)" >> $GITHUB_OUTPUT 

      - name: Restore
        run: dotnet restore ${{ steps.locate-project.outputs.PROJECT_FILENAME }}

      - name: Pack
        run: >-
          dotnet pack  ${{ steps.locate-project.outputs.PROJECT_FILENAME }}
          --no-restore
          -c Release
          -p:Version=${{ env.CALCULATED_VERSION }}
      
      - name: NuGet push
        run: dotnet nuget push artifacts/package/release/${{ matrix.project }}.${{ env.CALCULATED_VERSION }}.nupkg --api-key ${{steps.nuget-login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
